// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlgoFilter(arg1) {
  return window['go']['backend']['App']['AlgoFilter'](arg1);
}

export function AlgoProduct(arg1) {
  return window['go']['backend']['App']['AlgoProduct'](arg1);
}

export function ArticleDetail(arg1, arg2) {
  return window['go']['backend']['App']['ArticleDetail'](arg1, arg2);
}

export function ArticleList(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['ArticleList'](arg1, arg2, arg3, arg4);
}

export function AudioDetail(arg1) {
  return window['go']['backend']['App']['AudioDetail'](arg1);
}

export function BookKnowledgeChat(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['BookKnowledgeChat'](arg1, arg2, arg3, arg4);
}

export function BookKnowledgeChatHistory(arg1, arg2) {
  return window['go']['backend']['App']['BookKnowledgeChatHistory'](arg1, arg2);
}

export function BookKnowledgeExport(arg1, arg2) {
  return window['go']['backend']['App']['BookKnowledgeExport'](arg1, arg2);
}

export function BookKnowledgeGetBook(arg1) {
  return window['go']['backend']['App']['BookKnowledgeGetBook'](arg1);
}

export function BookKnowledgeListBooks() {
  return window['go']['backend']['App']['BookKnowledgeListBooks']();
}

export function BookKnowledgeMCPCall(arg1, arg2) {
  return window['go']['backend']['App']['BookKnowledgeMCPCall'](arg1, arg2);
}

export function BookKnowledgeMCPTools() {
  return window['go']['backend']['App']['BookKnowledgeMCPTools']();
}

export function BookKnowledgeNotebookLMBridge(arg1) {
  return window['go']['backend']['App']['BookKnowledgeNotebookLMBridge'](arg1);
}

export function BookKnowledgeNotebookLMExport(arg1) {
  return window['go']['backend']['App']['BookKnowledgeNotebookLMExport'](arg1);
}

export function BookKnowledgeNotebookLMSaveLink(arg1, arg2) {
  return window['go']['backend']['App']['BookKnowledgeNotebookLMSaveLink'](arg1, arg2);
}

export function BookKnowledgeRoot() {
  return window['go']['backend']['App']['BookKnowledgeRoot']();
}

export function BookKnowledgeSearch(arg1, arg2, arg3) {
  return window['go']['backend']['App']['BookKnowledgeSearch'](arg1, arg2, arg3);
}

export function CheckLogin(arg1, arg2) {
  return window['go']['backend']['App']['CheckLogin'](arg1, arg2);
}

export function CourseCategory() {
  return window['go']['backend']['App']['CourseCategory']();
}

export function CourseDownload(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['CourseDownload'](arg1, arg2, arg3, arg4);
}

export function CourseInfo(arg1) {
  return window['go']['backend']['App']['CourseInfo'](arg1);
}

export function CourseList(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['CourseList'](arg1, arg2, arg3, arg4);
}

export function EbookCommentList(arg1, arg2, arg3) {
  return window['go']['backend']['App']['EbookCommentList'](arg1, arg2, arg3);
}

export function EbookDownload(arg1, arg2, arg3) {
  return window['go']['backend']['App']['EbookDownload'](arg1, arg2, arg3);
}

export function EbookDownloadAndSyncWiki(arg1, arg2) {
  return window['go']['backend']['App']['EbookDownloadAndSyncWiki'](arg1, arg2);
}

export function EbookInfo(arg1) {
  return window['go']['backend']['App']['EbookInfo'](arg1);
}

export function EbookShelfAdd(arg1) {
  return window['go']['backend']['App']['EbookShelfAdd'](arg1);
}

export function EbookShelfRemove(arg1) {
  return window['go']['backend']['App']['EbookShelfRemove'](arg1);
}

export function EbookUserInfo() {
  return window['go']['backend']['App']['EbookUserInfo']();
}

export function GetHomeInitialState() {
  return window['go']['backend']['App']['GetHomeInitialState']();
}

export function GetQrcode() {
  return window['go']['backend']['App']['GetQrcode']();
}

export function GetVolcPlayAuthToken(arg1, arg2) {
  return window['go']['backend']['App']['GetVolcPlayAuthToken'](arg1, arg2);
}

export function GetVolcPlayInfo(arg1) {
  return window['go']['backend']['App']['GetVolcPlayInfo'](arg1);
}

export function Logout() {
  return window['go']['backend']['App']['Logout']();
}

export function NotesTimeline(arg1) {
  return window['go']['backend']['App']['NotesTimeline'](arg1);
}

export function OdobDownload(arg1, arg2, arg3) {
  return window['go']['backend']['App']['OdobDownload'](arg1, arg2, arg3);
}

export function OdobShelfAdd(arg1) {
  return window['go']['backend']['App']['OdobShelfAdd'](arg1);
}

export function OdobUserInfo() {
  return window['go']['backend']['App']['OdobUserInfo']();
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['backend']['App']['OpenDirectoryDialog'](arg1);
}

export function SearchHot() {
  return window['go']['backend']['App']['SearchHot']();
}

export function SetDir(arg1) {
  return window['go']['backend']['App']['SetDir'](arg1);
}

export function SunflowerLabelContent(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['SunflowerLabelContent'](arg1, arg2, arg3, arg4);
}

export function SunflowerLabelList(arg1) {
  return window['go']['backend']['App']['SunflowerLabelList'](arg1);
}

export function SunflowerResourceList() {
  return window['go']['backend']['App']['SunflowerResourceList']();
}

export function TopicAll(arg1, arg2) {
  return window['go']['backend']['App']['TopicAll'](arg1, arg2);
}

export function TopicNoteDetail(arg1) {
  return window['go']['backend']['App']['TopicNoteDetail'](arg1);
}

export function TopicNotesList(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['TopicNotesList'](arg1, arg2, arg3, arg4);
}

export function UserInfo() {
  return window['go']['backend']['App']['UserInfo']();
}
